// A DirectedCycle is a pointer to an allowed twist in the original puzzle
// cycleIndex is the index in the original puzzle of some "Cycle"
// The direction integer represent how many times the twist has to be applied forward/backward
// Sequence & SubSequence represent some useful metadata about the move sequences generated by the solver for ease of analysis
class DirectedCycle {
  constructor(cycleIndex, period, direction, sequence, subSequence) {
    this.cycleIndex = cycleIndex;
    this.period = period;
    this.direction = direction;
    this.sequence = sequence;
    this.subSequence = subSequence;
  }
}
